
```{r}
install.packages("name")
library(name)
install.packages("MASS")
library(MASS)
install.packages("dplyr")
library(dplyr)
```

```{r}
# Distribution estimation
nhanes_subset <- NHANES %>%
    filter(Age > 18 & Gender == "male")
n_height <- sum(complete.cases(nhanes_subset$Height))
nhanes_height <- na.omit(nhanes_subset$Height)

normal_params <- fitdistr(nhanes_height, "normal")
weibull_params <- fitdistr(nhanes_height, "weibull", list(shape=20, scale=200)) #shape / scale are initial estimates for distribution

height_min <- min(nhanes_height)
height_max <- max(nhanes_height)
x_pdf <- seq(height_min, height_max, 1)

y_norm <- dnorm(x_pdf,normal_params$estimate["mean"],normal_params$estimate["sd"])
y_weib <- dweibull(x_pdf,weibull_params$estimate["shape"],weibull_params$estimate["scale"])

# Histogram - lot density
hist(nhanes_height, freq = FALSE, xlab="Height",ylab="Density")
lines(x_pdf,y_norm,col="blue")
lines(x_pdf,y_weib,col="red")
legend(x="topleft",c("normal","weibul"),col=c("blue","red"),lty=1,cex=1)

N <- 1000
norm_sample <- rnorm(N,normal_params$estimate["mean"],normal_params$estimate["sd"])
weib_sample <- rweibull(N,weibull_params$estimate["shape"],weibull_params$estimate["scale"])

col1 <- rgb(20,23,219,max=255,alpha=100) #blue
col2 <- rgb(219,20,20,max=255,alpha=100) #red

h1 <- hist(norm_sample, plot=FALSE)
h2 <- hist(weib_sample, plot=FALSE)

plot(h1, col=col1,xlab="Height",ylab="Freq",main="Sampling")
plot(h2,col=col2,add=TRUE)
legend(x="topleft",c("normal","weibull"),fill=c("blue","red"))

normal_params #output of μ and σ^2
weibull_params #output of shape and scale

```